<template>
    <div class="generate-playlist mt-4">
        <h5>Playlist Scheduler</h5>
        <p>Automatically generate custom Spotify playlists for each of your streams based on your fan's favorite songs and what you're streaming.</p>

        <div class="schedule">
            <div class="form-inline" v-for="(playlist, index) in playlists">
                <div class="form-group mb-3">
                    <template v-if="playlist.id">
                        <font-awesome-icon icon="times" class="fa-fw text-danger" @click="removePlaylist(index)" />
                    </template>
                    <template v-else>
                        <font-awesome-icon
                            icon="check"
                            :class="'fa-fw ' + ((playlist.game && playlist.day && playlist.start_time && playlist.length) ? 'text-success' : 'text-muted')"
                            @click="generatePlaylist(index)"
                        />
                    </template>
                </div>
                <div class="form-group mx-2 mb-3">
                    <input type="text" class="form-control-plaintext" v-model="playlist.game" placeholder="game">
                </div>
                <div class="form-group mx-2 mb-3">
                    <select class="form-control-plaintext" v-model="playlist.day" :class="{placeholder: playlist.day == ''}">
                        <option value="" disabled hidden>day of week</option>
                        <option>Monday</option>
                        <option>Tuesday</option>
                        <option>Wednesday</option>
                        <option>Thursday</option>
                        <option>Friday</option>
                        <option>Saturday</option>
                        <option>Sunday</option>
                    </select>
                </div>
                <div class="form-group mx-2 ml-xs-175 mb-3">
                    <timepicker input-class="form-control-plaintext" v-model="playlist.start_time" format="hh:mm A" placeholder="start time"></timepicker>
                </div>
                <div class="form-group mx-2 mb-3">
                    <timepicker input-class="form-control-plaintext" v-model="playlist.length" format="hh hours mm minutes" placeholder="length"></timepicker>
                </div>
            </div>
        </div>

        <div class="form-inline">
            <div class="form-group mb-3">
                <font-awesome-icon icon="plus" class="fa-fw text-info" @click="addEmptyPlaylist" />
            </div>
        </div>
    </div>
</template>

<script>
    import Timepicker from './../common/Timepicker';

    export default {
        name: 'GeneratePlaylistForm',

        components: {
            Timepicker
        },

        data () {
            return {
                playlists: []   // Playlists generated by Gethr.
            };
        },

        created () {
            this.getPlaylists();
        },

        methods: {
            /**
             * Add an empty playlist.
             *
             * @return {void}
             */
            addEmptyPlaylist () {
                this.playlists.push({
                    game: '',
                    day: '',
                    start_time: '',
                    length: ''
                });
            },

            /**
             * Fires off a request to the EBS so a new playlist with the given name can be generated.
             *
             * @return {void}
             */
            generatePlaylist (index) {
                let playlist = this.playlists[index];

                if (!playlist.game || !playlist.day || !playlist.start_time || !playlist.length) {
                    return;
                }

                this.$http.post(`${this.urls.Ebs}/spotify/playlists`, {
                    game: playlist.game,
                    day: playlist.day,
                    start_time: playlist.start_time,
                    length: playlist.length
                })
                .then(response => this.getPlaylists())
                .catch(error => this.error(error));
            },

            /**
             * Gets the broadcaster's playlists from the EBS.
             *
             * @return {void}
             */
            getPlaylists () {
                // TODO: Disabled by Aldrin
                if (false) {
                    this.$http.get(`${this.urls.Ebs}/spotify/playlists`)
                        .then(response => {
                            if (response.data) {
                                this.playlists = response.data;
                            }
                        })
                        .catch(error => this.error(error));
                }
            },

            /**
             * Removes a playlist.
             *
             * @param  {Number}  index
             * @return {void}
             */
            removePlaylist (index) {
                let playlist = this.playlists[index];

                this.$http.delete(`${this.urls.Ebs}/spotify/playlists/${playlist.id}`)
                .then(response => this.playlists.splice(index, 1))
                .catch(error => this.error(error));
            }
        }
    }
</script>
